---
title: "Dimensionality Reduction"
author: "Mubarak Ganiyu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Package Installation

```{r}
library(tidymodels)
tidymodels_prefer()
library(beans)
```

```{r}
set.seed(1601)
bean_split <- initial_split(beans, strata = class, prop = 3/4)

bean_train <- training(bean_split)
bean_test  <- testing(bean_split)

set.seed(1602)
bean_val <- validation_split(bean_train, strata = class, prop = 4/5)
bean_val$splits[[1]]
```

```{r}
library(corrplot)
tmwr_cols <- colorRampPalette(c("#91CBD765", "#CA225E"))
bean_train %>%
  select(-class) %>%
  cor() %>%
  corrplot(col = tmwr_cols(200), tl.col = "black", method = "ellipse")
```

#### A starter Recipe

```{r}
library(bestNormalize)
bean_rec <-
  # Use the training data from the bean_val split object
  recipe(class ~ ., data = analysis(bean_val$splits[[1]])) %>%
  step_zv(all_numeric_predictors()) %>%
  step_orderNorm(all_numeric_predictors()) %>%
  step_normalize(all_numeric_predictors())
```

#### Recipes in the Wild

##### Preparing a Recipe

```{r}
bean_rec_trained <- prep(bean_rec)
bean_rec_trained
```

```{r}
show_variables <-
  bean_rec %>%
  prep(log_changes = TRUE)
```

#### Baking the recipe

```{r}
bean_validation <- bean_val$splits %>% pluck(1) %>% assessment()
bean_val_processed <- bake(bean_rec_trained, new_data = bean_validation)
```

```{r}
library(patchwork)
p1 <-
  bean_validation %>%
  ggplot(aes(x = area)) +
  geom_histogram(bins = 30, color = "white", fill = "blue", alpha = 1/3) +
  ggtitle("Original validation set data")

p2 <-
  bean_val_processed %>%
  ggplot(aes(x = area)) +
  geom_histogram(bins = 30, color = "white", fill = "red", alpha = 1/3) +
  ggtitle("Processed validation set data")

p1 + p2
```

```{r}
bake(bean_rec_trained, new_data = NULL) %>% nrow()
bean_val$splits %>% pluck(1) %>% analysis() %>% nrow()
```
#### Feature Extraction Techniques

```{r}
plot_validation_results <- function(recipe, dat = assessment(bean_val$splits[[1]])) {
  set.seed(1)
  plot_data <-
    recipe %>%
    # Estimate any additional steps
    prep() %>%
    # Process the data (the validation set by default)
    bake(new_data = dat, all_predictors(), all_outcomes()) %>%
    # Sample the data down to be more readable
    sample_n(250)

  # Convert feature names to symbols to use with quasiquotation
  nms <- names(plot_data)
  x_name <- sym(nms[1])
  y_name <- sym(nms[2])

  plot_data %>%
    ggplot(aes(x = !!x_name, y = !!y_name, col = class,
               fill = class, pch = class)) +
    geom_point(alpha = 0.9) +
    scale_shape_manual(values = 1:7) +
    # Make equally sized axes
    coord_obs_pred() +
    theme_bw()
}
```


#### Principal Component Analysis

```{r}
bean_rec_trained %>%
  step_pca(all_numeric_predictors(), num_comp = 4) %>%
  plot_validation_results() +
  ggtitle("Principal Component Analysis")
```

```{r}
bean_rec_trained %>%
  step_pca(all_numeric_predictors(), num_comp = 4) %>%
  plot_validation_results() +
  ggtitle("Principal Component Analysis")
```

```{r}
# library(learntidymodels)
# bean_rec_trained %>%
#   step_pca(all_numeric_predictors(), num_comp = 4) %>%
#   prep() %>%
#   plot_top_loadings(component_number <= 4, n = 5) +
#   scale_fill_brewer(palette = "Paired") +
#   ggtitle("Principal Component Analysis")
```

#### Partial Least Squares

```{r}
bean_rec_trained %>%
  step_pls(all_numeric_predictors(), outcome = "class", num_comp = 4) %>%
  plot_validation_results() +
  ggtitle("Partial Least Squares")
```

```{r}
# bean_rec_trained %>%
#   step_pls(all_numeric_predictors(), outcome = "class", num_comp = 4) %>%
#   prep() %>%
#   plot_top_loadings(component_number <= 4, n = 5, type = "pls") +
#   scale_fill_brewer(palette = "Paired") +
#   ggtitle("Partial Least Squares")
```

#### Independent Component Analysis

```{r}
library(fastICA)
bean_rec_trained %>%
  step_ica(all_numeric_predictors(), num_comp = 4) %>%
  plot_validation_results() +
  ggtitle("Independent Component Analysis")
```

#### Uniform manifold approximation and projection

```{r}
library(embed)
bean_rec_trained %>%
  step_umap(all_numeric_predictors(), num_comp = 4) %>%
  plot_validation_results() +
  ggtitle("UMAP")
```

```{r}
bean_rec_trained %>%
  step_umap(all_numeric_predictors(), outcome = "class", num_comp = 4) %>%
  plot_validation_results() +
  ggtitle("UMAP (supervised)")
```

#### Modeling

```{r}
library(baguette)
library(discrim)

mlp_spec <-
  mlp(hidden_units = tune(), penalty = tune(), epochs = tune()) %>%
  set_engine('nnet') %>%
  set_mode('classification')

bagging_spec <-
  bag_tree() %>%
  set_engine('rpart') %>%
  set_mode('classification')

fda_spec <-
  discrim_flexible(
    prod_degree = tune()
  ) %>%
  set_engine('earth')

rda_spec <-
  discrim_regularized(frac_common_cov = tune(), frac_identity = tune()) %>%
  set_engine('klaR')

bayes_spec <-
  naive_Bayes() %>%
  set_engine('klaR')
```


```{r}
bean_rec <-
  recipe(class ~ ., data = bean_train) %>%
  step_zv(all_numeric_predictors()) %>%
  step_orderNorm(all_numeric_predictors()) %>%
  step_normalize(all_numeric_predictors())

# pls_rec <-
#   bean_rec %>%
#  # step_pls(all_numeric_predictors(), outcome = "class", num_comp = tune())

umap_rec <-
  bean_rec %>%
  step_umap(
    all_numeric_predictors(),
    outcome = "class",
    num_comp = tune(),
    neighbors = tune(),
    min_dist = tune()
  )
```

```{r}
ctrl <- control_grid(parallel_over = "everything")
bean_res <-
  workflow_set(
    preproc = list(basic = class ~., umap = umap_rec),
    models = list(bayes = bayes_spec, fda = fda_spec,
                  rda = rda_spec, bag = bagging_spec,
                  mlp = mlp_spec)
  ) %>%
  workflow_map(
    verbose = TRUE,
    seed = 1603,
    resamples = bean_val,
    grid = 3,
    metrics = metric_set(roc_auc),
    control = ctrl
  )
```

```{r}
rankings <-
  rank_results(bean_res, select_best = TRUE) %>%
  mutate(method = map_chr(wflow_id, ~ stringr::str_split(.x, "_", simplify = TRUE)[1]))

tidymodels_prefer()
filter(rankings, rank <= 5) %>% dplyr::select(rank, mean, model, method)
```

```{r}
basic_mlp <-
  bean_res %>%
  extract_workflow("basic_mlp") %>%
  finalize_workflow(
    bean_res %>%
      extract_workflow_set_result("basic_mlp") %>%
      select_best(metric = "roc_auc")
  ) %>%
  last_fit(split = bean_split, metrics = metric_set(roc_auc))

basic_wflow_fit <- basic_mlp$.workflow[[1]]
```

```{r}
collect_metrics(basic_mlp)
```

